# Generated by Django 6.0.1 on 2026-02-16 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boys_id', models.CharField(max_length=100, unique=True)),
                ('girls_id', models.CharField(max_length=100, unique=True)),
                ('kides_id', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'master_category',
            },
        ),
        migrations.CreateModel(
            name='sub_boys_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sports_shoes_identify', models.CharField(max_length=100, unique=True)),
                ('casual_shoes_identify', models.CharField(max_length=100, unique=True)),
                ('pary_shoes_identify', models.CharField(max_length=100, unique=True)),
                ('runnig_shoes_identify', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('master_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='api.master_category')),
            ],
            options={
                'db_table': 'sub_boys_category',
            },
        ),
        migrations.CreateModel(
            name='Casual_Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('b_c_s_image', models.URLField(blank=True, max_length=500, null=True)),
                ('b_c_s_description', models.TextField()),
                ('b_c_s_size', models.CharField(max_length=50)),
                ('b_c_s_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('b_c_s_slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_boyes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casual_shoes_boys', to='api.sub_boys_category')),
            ],
            options={
                'db_table': 'casual_shoes_boys',
            },
        ),
        migrations.CreateModel(
            name='sub_girls_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sports_shoes_identify', models.CharField(max_length=100, unique=True)),
                ('casual_shoes_identify', models.CharField(max_length=100, unique=True)),
                ('pary_shoes_identify', models.CharField(max_length=100, unique=True)),
                ('runnig_shoes_identify', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('master_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_girls_categories', to='api.master_category')),
            ],
            options={
                'db_table': 'sub_girls_category',
            },
        ),
        migrations.CreateModel(
            name='sub_kids_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sports_shoes_identify', models.CharField(max_length=100, unique=True)),
                ('casual_shoes_identify', models.CharField(max_length=100, unique=True)),
                ('pary_shoes_identify', models.CharField(max_length=100, unique=True)),
                ('runnig_shoes_identify', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('master_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_kids_categories', to='api.master_category')),
            ],
            options={
                'db_table': 'sub_kids_category',
            },
        ),
    ]
