# Generated by Django 6.0.1 on 2026-02-17 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_master_category_sub_boys_category_casual_shoes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='master_category',
            old_name='boys_id',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='master_category',
            name='girls_id',
        ),
        migrations.RemoveField(
            model_name='master_category',
            name='kides_id',
        ),
    ]
