# Generated by Django 6.0.1 on 2026-02-18 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_boys_id_master_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_boys_category',
            name='master_category',
        ),
        migrations.RemoveField(
            model_name='sub_girls_category',
            name='master_category',
        ),
        migrations.RemoveField(
            model_name='sub_kids_category',
            name='master_category',
        ),
        migrations.RenameModel(
            old_name='Master_Category',
            new_name='MasterCategory',
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('master_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='api.mastercategory')),
            ],
            options={
                'db_table': 'sub_category',
                'unique_together': {('master_category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('size', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.subcategory')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.DeleteModel(
            name='Casual_Shoes',
        ),
        migrations.DeleteModel(
            name='sub_boys_category',
        ),
        migrations.DeleteModel(
            name='sub_girls_category',
        ),
        migrations.DeleteModel(
            name='sub_kids_category',
        ),
    ]
