# Generated by Django 6.0.1 on 2026-02-18 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_sub_boys_category_master_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mastercategory',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='active',
            new_name='is_active',
        ),
    ]
