# Generated by Django 6.0.1 on 2026-04-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_remove_product_size_product_base_sku_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("c_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "c_mobile",
                    models.CharField(blank=True, max_length=15, null=True, unique=True),
                ),
                (
                    "c_email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("c_login_time", models.TimeField(blank=True, null=True)),
                ("c_profile", models.FileField(blank=True, null=True, upload_to="")),
                ("c_address", models.CharField(blank=True, max_length=100, null=True)),
                ("c_city", models.CharField(blank=True, max_length=100, null=True)),
                ("c_state", models.CharField(blank=True, max_length=100, null=True)),
                ("c_pin", models.CharField(blank=True, max_length=10, null=True)),
                ("cretated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "customer_details",
            },
        ),
    ]
