# Generated by Django 6.0.1 on 2026-05-13 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_customerdetails"),
        ("api", "0009_product_tags"),
    ]

    operations = []
