--
-- PostgreSQL database dump
--

\restrict 58d8MixNif57Uh6ggGd6BFmqTi8PE7V4obmLYs5KMnpxW7auNOmrIdwzg7BEIy0

-- Dumped from database version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: nike
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO nike;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: nike
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: nike
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO nike;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: nike
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: nike
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO nike;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: nike
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customer_details; Type: TABLE; Schema: public; Owner: nike
--

CREATE TABLE public.customer_details (
    id bigint NOT NULL,
    c_name character varying(100),
    c_mobile character varying(15),
    c_email character varying(254),
    c_login_time time without time zone,
    c_profile character varying(100),
    c_address character varying(100),
    c_city character varying(100),
    c_state character varying(100),
    c_pin character varying(10),
    cretated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.customer_details OWNER TO nike;

--
-- Name: customer_details_id_seq; Type: SEQUENCE; Schema: public; Owner: nike
--

ALTER TABLE public.customer_details ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_details_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: nike
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO nike;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: nike
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: nike
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO nike;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: nike
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: nike
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO nike;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: nike
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: nike
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO nike;

--
-- Name: master_category; Type: TABLE; Schema: public; Owner: nike
--

CREATE TABLE public.master_category (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    is_active boolean NOT NULL,
    slug character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.master_category OWNER TO nike;

--
-- Name: master_category_id_seq; Type: SEQUENCE; Schema: public; Owner: nike
--

ALTER TABLE public.master_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.master_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product; Type: TABLE; Schema: public; Owner: nike
--

CREATE TABLE public.product (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    description text NOT NULL,
    price numeric(10,2),
    image character varying(100),
    slug character varying(50) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    sub_category_id bigint NOT NULL,
    base_sku character varying(100) NOT NULL,
    compare_at_price numeric(10,2),
    is_featured boolean NOT NULL,
    options jsonb NOT NULL,
    product_type character varying(20) NOT NULL,
    short_description character varying(255) NOT NULL,
    sku character varying(100),
    stock_quantity integer NOT NULL,
    track_quantity boolean NOT NULL,
    tags jsonb NOT NULL,
    CONSTRAINT product_stock_quantity_check CHECK ((stock_quantity >= 0))
);


ALTER TABLE public.product OWNER TO nike;

--
-- Name: product_id_seq; Type: SEQUENCE; Schema: public; Owner: nike
--

ALTER TABLE public.product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_image; Type: TABLE; Schema: public; Owner: nike
--

CREATE TABLE public.product_image (
    id bigint NOT NULL,
    image character varying(100) NOT NULL,
    alt_text character varying(255) NOT NULL,
    sort_order integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    product_id bigint NOT NULL,
    CONSTRAINT product_image_sort_order_check CHECK ((sort_order >= 0))
);


ALTER TABLE public.product_image OWNER TO nike;

--
-- Name: product_image_id_seq; Type: SEQUENCE; Schema: public; Owner: nike
--

ALTER TABLE public.product_image ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_image_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_variant; Type: TABLE; Schema: public; Owner: nike
--

CREATE TABLE public.product_variant (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    sku character varying(100) NOT NULL,
    attributes jsonb NOT NULL,
    price numeric(10,2) NOT NULL,
    compare_at_price numeric(10,2),
    stock_quantity integer NOT NULL,
    track_quantity boolean NOT NULL,
    is_active boolean NOT NULL,
    sort_order integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    product_id bigint NOT NULL,
    CONSTRAINT product_variant_sort_order_check CHECK ((sort_order >= 0)),
    CONSTRAINT product_variant_stock_quantity_check CHECK ((stock_quantity >= 0))
);


ALTER TABLE public.product_variant OWNER TO nike;

--
-- Name: product_variant_id_seq; Type: SEQUENCE; Schema: public; Owner: nike
--

ALTER TABLE public.product_variant ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_variant_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_variant_image; Type: TABLE; Schema: public; Owner: nike
--

CREATE TABLE public.product_variant_image (
    id bigint NOT NULL,
    image character varying(100) NOT NULL,
    sort_order integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    variant_id bigint NOT NULL,
    CONSTRAINT product_variant_image_sort_order_check CHECK ((sort_order >= 0))
);


ALTER TABLE public.product_variant_image OWNER TO nike;

--
-- Name: product_variant_image_id_seq; Type: SEQUENCE; Schema: public; Owner: nike
--

ALTER TABLE public.product_variant_image ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_variant_image_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sub_category; Type: TABLE; Schema: public; Owner: nike
--

CREATE TABLE public.sub_category (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    is_active boolean NOT NULL,
    slug character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    master_category_id bigint NOT NULL,
    description text NOT NULL,
    image character varying(100)
);


ALTER TABLE public.sub_category OWNER TO nike;

--
-- Name: sub_category_id_seq; Type: SEQUENCE; Schema: public; Owner: nike
--

ALTER TABLE public.sub_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sub_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token_blacklist_blacklistedtoken; Type: TABLE; Schema: public; Owner: nike
--

CREATE TABLE public.token_blacklist_blacklistedtoken (
    id bigint NOT NULL,
    blacklisted_at timestamp with time zone NOT NULL,
    token_id bigint NOT NULL
);


ALTER TABLE public.token_blacklist_blacklistedtoken OWNER TO nike;

--
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: nike
--

ALTER TABLE public.token_blacklist_blacklistedtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_blacklistedtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token_blacklist_outstandingtoken; Type: TABLE; Schema: public; Owner: nike
--

CREATE TABLE public.token_blacklist_outstandingtoken (
    id bigint NOT NULL,
    token text NOT NULL,
    created_at timestamp with time zone,
    expires_at timestamp with time zone NOT NULL,
    user_id bigint,
    jti character varying(255) NOT NULL
);


ALTER TABLE public.token_blacklist_outstandingtoken OWNER TO nike;

--
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: nike
--

ALTER TABLE public.token_blacklist_outstandingtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_outstandingtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: nike
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    username character varying(100),
    email character varying(254),
    phone character varying(15),
    role character varying(10) NOT NULL,
    is_verified boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.users OWNER TO nike;

--
-- Name: users_groups; Type: TABLE; Schema: public; Owner: nike
--

CREATE TABLE public.users_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.users_groups OWNER TO nike;

--
-- Name: users_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: nike
--

ALTER TABLE public.users_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: nike
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_permissions; Type: TABLE; Schema: public; Owner: nike
--

CREATE TABLE public.users_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.users_user_permissions OWNER TO nike;

--
-- Name: users_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: nike
--

ALTER TABLE public.users_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: nike
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: nike
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: nike
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add user	6	add_user
22	Can change user	6	change_user
23	Can delete user	6	delete_user
24	Can view user	6	view_user
25	Can add Blacklisted Token	7	add_blacklistedtoken
26	Can change Blacklisted Token	7	change_blacklistedtoken
27	Can delete Blacklisted Token	7	delete_blacklistedtoken
28	Can view Blacklisted Token	7	view_blacklistedtoken
29	Can add Outstanding Token	8	add_outstandingtoken
30	Can change Outstanding Token	8	change_outstandingtoken
31	Can delete Outstanding Token	8	delete_outstandingtoken
32	Can view Outstanding Token	8	view_outstandingtoken
33	Can add sub_girls_category	12	add_sub_girls_category
34	Can change sub_girls_category	12	change_sub_girls_category
35	Can delete sub_girls_category	12	delete_sub_girls_category
36	Can view sub_girls_category	12	view_sub_girls_category
37	Can add sub_kids_category	13	add_sub_kids_category
38	Can change sub_kids_category	13	change_sub_kids_category
39	Can delete sub_kids_category	13	delete_sub_kids_category
40	Can view sub_kids_category	13	view_sub_kids_category
41	Can add sub_boys_category	11	add_sub_boys_category
42	Can change sub_boys_category	11	change_sub_boys_category
43	Can delete sub_boys_category	11	delete_sub_boys_category
44	Can view sub_boys_category	11	view_sub_boys_category
45	Can add casual_ shoes	9	add_casual_shoes
46	Can change casual_ shoes	9	change_casual_shoes
47	Can delete casual_ shoes	9	delete_casual_shoes
48	Can view casual_ shoes	9	view_casual_shoes
49	Can add master_ category	10	add_master_category
50	Can change master_ category	10	change_master_category
51	Can delete master_ category	10	delete_master_category
52	Can view master_ category	10	view_master_category
53	Can add master category	10	add_mastercategory
54	Can change master category	10	change_mastercategory
55	Can delete master category	10	delete_mastercategory
56	Can view master category	10	view_mastercategory
57	Can add sub category	15	add_subcategory
58	Can change sub category	15	change_subcategory
59	Can delete sub category	15	delete_subcategory
60	Can view sub category	15	view_subcategory
61	Can add product	14	add_product
62	Can change product	14	change_product
63	Can delete product	14	delete_product
64	Can view product	14	view_product
65	Can add product image	16	add_productimage
66	Can change product image	16	change_productimage
67	Can delete product image	16	delete_productimage
68	Can view product image	16	view_productimage
69	Can add product variant	17	add_productvariant
70	Can change product variant	17	change_productvariant
71	Can delete product variant	17	delete_productvariant
72	Can view product variant	17	view_productvariant
73	Can add product variant image	18	add_productvariantimage
74	Can change product variant image	18	change_productvariantimage
75	Can delete product variant image	18	delete_productvariantimage
76	Can view product variant image	18	view_productvariantimage
77	Can add customer details	19	add_customerdetails
78	Can change customer details	19	change_customerdetails
79	Can delete customer details	19	delete_customerdetails
80	Can view customer details	19	view_customerdetails
\.


--
-- Data for Name: customer_details; Type: TABLE DATA; Schema: public; Owner: nike
--

COPY public.customer_details (id, c_name, c_mobile, c_email, c_login_time, c_profile, c_address, c_city, c_state, c_pin, cretated_at) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: nike
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: nike
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	contenttypes	contenttype
5	sessions	session
6	api	user
7	token_blacklist	blacklistedtoken
8	token_blacklist	outstandingtoken
9	api	casual_shoes
11	api	sub_boys_category
12	api	sub_girls_category
13	api	sub_kids_category
10	api	mastercategory
14	api	product
15	api	subcategory
16	api	productimage
17	api	productvariant
18	api	productvariantimage
19	api	customerdetails
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: nike
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-02-04 14:24:19.033973+05:30
2	contenttypes	0002_remove_content_type_name	2026-02-04 14:24:19.040513+05:30
3	auth	0001_initial	2026-02-04 14:24:19.071812+05:30
4	auth	0002_alter_permission_name_max_length	2026-02-04 14:24:19.07671+05:30
5	auth	0003_alter_user_email_max_length	2026-02-04 14:24:19.080254+05:30
6	auth	0004_alter_user_username_opts	2026-02-04 14:24:19.084136+05:30
7	auth	0005_alter_user_last_login_null	2026-02-04 14:24:19.089276+05:30
8	auth	0006_require_contenttypes_0002	2026-02-04 14:24:19.091253+05:30
9	auth	0007_alter_validators_add_error_messages	2026-02-04 14:24:19.096516+05:30
10	auth	0008_alter_user_username_max_length	2026-02-04 14:24:19.100928+05:30
11	auth	0009_alter_user_last_name_max_length	2026-02-04 14:24:19.105262+05:30
12	auth	0010_alter_group_name_max_length	2026-02-04 14:24:19.109031+05:30
13	auth	0011_update_proxy_permissions	2026-02-04 14:24:19.11238+05:30
14	auth	0012_alter_user_first_name_max_length	2026-02-04 14:24:19.115847+05:30
15	api	0001_initial	2026-02-04 14:24:19.139046+05:30
16	admin	0001_initial	2026-02-04 14:24:19.150323+05:30
17	admin	0002_logentry_remove_auto_add	2026-02-04 14:24:19.156385+05:30
18	admin	0003_logentry_add_action_flag_choices	2026-02-04 14:24:19.161455+05:30
19	sessions	0001_initial	2026-02-04 14:24:19.169751+05:30
20	token_blacklist	0001_initial	2026-02-04 14:24:19.189804+05:30
21	token_blacklist	0002_outstandingtoken_jti_hex	2026-02-04 14:24:19.195666+05:30
22	token_blacklist	0003_auto_20171017_2007	2026-02-04 14:24:19.204984+05:30
23	token_blacklist	0004_auto_20171017_2013	2026-02-04 14:24:19.220925+05:30
24	token_blacklist	0005_remove_outstandingtoken_jti	2026-02-04 14:24:19.233773+05:30
25	token_blacklist	0006_auto_20171017_2113	2026-02-04 14:24:19.242898+05:30
26	token_blacklist	0007_auto_20171017_2214	2026-02-04 14:24:19.267643+05:30
27	token_blacklist	0008_migrate_to_bigautofield	2026-02-04 14:24:19.299361+05:30
28	token_blacklist	0010_fix_migrate_to_bigautofield	2026-02-04 14:24:19.313182+05:30
29	token_blacklist	0011_linearizes_history	2026-02-04 14:24:19.314956+05:30
30	token_blacklist	0012_alter_outstandingtoken_user	2026-02-04 14:24:19.324583+05:30
31	token_blacklist	0013_alter_blacklistedtoken_options_and_more	2026-02-04 14:24:19.333773+05:30
32	api	0002_alter_user_managers_alter_user_email_and_more	2026-02-04 15:04:01.13476+05:30
33	api	0002_master_category_sub_boys_category_casual_shoes_and_more	2026-02-16 11:29:30.709595+05:30
34	api	0003_rename_boys_id_master_category_name_and_more	2026-02-18 09:37:06.916104+05:30
35	api	0004_remove_sub_boys_category_master_category_and_more	2026-02-18 09:37:06.990933+05:30
36	api	0005_rename_active_mastercategory_is_active_and_more	2026-02-18 11:10:03.020569+05:30
37	api	0006_alter_product_image	2026-05-13 12:55:14.954345+05:30
38	api	0007_subcategory_description_subcategory_image_and_more	2026-05-13 12:55:14.973942+05:30
39	api	0008_remove_product_size_product_base_sku_and_more	2026-05-13 12:55:15.042404+05:30
40	api	0009_product_tags	2026-05-13 12:55:15.047196+05:30
41	api	0009_customerdetails	2026-07-13 16:23:10.450895+05:30
42	api	0010_merge_0009_customerdetails_0009_product_tags	2026-07-13 16:23:10.452473+05:30
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: nike
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- Data for Name: master_category; Type: TABLE DATA; Schema: public; Owner: nike
--

COPY public.master_category (id, name, is_active, slug, created_at, updated_at) FROM stdin;
1	Boyes Shoe	t	boyes-shoe	2026-02-18 11:12:35.540166+05:30	2026-02-18 11:12:35.540176+05:30
2	Men	t	men	2026-05-13 17:55:11.384337+05:30	2026-05-13 17:55:11.384348+05:30
3	Women	t	women	2026-05-13 17:55:28.792025+05:30	2026-05-13 17:55:28.792038+05:30
4	Kids	t	kids	2026-05-13 17:55:37.543689+05:30	2026-05-13 17:55:37.543696+05:30
\.


--
-- Data for Name: product; Type: TABLE DATA; Schema: public; Owner: nike
--

COPY public.product (id, name, description, price, image, slug, is_active, created_at, updated_at, sub_category_id, base_sku, compare_at_price, is_featured, options, product_type, short_description, sku, stock_quantity, track_quantity, tags) FROM stdin;
\.


--
-- Data for Name: product_image; Type: TABLE DATA; Schema: public; Owner: nike
--

COPY public.product_image (id, image, alt_text, sort_order, created_at, product_id) FROM stdin;
\.


--
-- Data for Name: product_variant; Type: TABLE DATA; Schema: public; Owner: nike
--

COPY public.product_variant (id, title, sku, attributes, price, compare_at_price, stock_quantity, track_quantity, is_active, sort_order, created_at, updated_at, product_id) FROM stdin;
\.


--
-- Data for Name: product_variant_image; Type: TABLE DATA; Schema: public; Owner: nike
--

COPY public.product_variant_image (id, image, sort_order, created_at, variant_id) FROM stdin;
\.


--
-- Data for Name: sub_category; Type: TABLE DATA; Schema: public; Owner: nike
--

COPY public.sub_category (id, name, is_active, slug, created_at, updated_at, master_category_id, description, image) FROM stdin;
1	Formal Men	t	formal-men	2026-05-13 17:56:27.735567+05:30	2026-05-13 17:56:27.735575+05:30	2	Testimg	sub-categories/Screenshot_from_2026-05-13_13-49-19.png
\.


--
-- Data for Name: token_blacklist_blacklistedtoken; Type: TABLE DATA; Schema: public; Owner: nike
--

COPY public.token_blacklist_blacklistedtoken (id, blacklisted_at, token_id) FROM stdin;
1	2026-02-05 11:09:05.336355+05:30	14
2	2026-03-13 14:53:29.599287+05:30	32
3	2026-03-13 15:20:18.20872+05:30	33
4	2026-05-13 16:11:29.159415+05:30	36
5	2026-05-13 16:15:22.056594+05:30	37
6	2026-05-13 16:29:41.986023+05:30	38
7	2026-05-13 16:31:02.022158+05:30	39
8	2026-05-13 16:31:47.786667+05:30	40
9	2026-05-13 17:40:40.746261+05:30	41
10	2026-05-13 17:53:22.737948+05:30	42
11	2026-05-14 10:54:03.057199+05:30	43
\.


--
-- Data for Name: token_blacklist_outstandingtoken; Type: TABLE DATA; Schema: public; Owner: nike
--

COPY public.token_blacklist_outstandingtoken (id, token, created_at, expires_at, user_id, jti) FROM stdin;
1	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3MDgwMzA3NSwiaWF0IjoxNzcwMTk4Mjc1LCJqdGkiOiJiOTIyMjQxYzQwM2E0NTZjYTE4ZmNhYTY4ZDQ3Y2JjMSIsInVzZXJfaWQiOiIyIn0.5sjIriEHuq7TBGBoFwHvt8GAn6x_uug-jMVih3HhoLk	2026-02-04 15:14:35.099588+05:30	2026-02-11 15:14:35+05:30	2	b922241c403a456ca18fcaa68d47cbc1
2	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3MDgwMzM5MywiaWF0IjoxNzcwMTk4NTkzLCJqdGkiOiI2NjM2ZTlmMjRkOTA0MWViOWRiYzU3NWE3MTZhNzZhZiIsInVzZXJfaWQiOiIyIn0.t82RCKCl3K7fPXCfYSYziJwOeorf-GNZjRdlEOP6wYY	2026-02-04 15:19:53.835127+05:30	2026-02-11 15:19:53+05:30	2	6636e9f24d9041eb9dbc575a716a76af
3	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3MDgwNDExNiwiaWF0IjoxNzcwMTk5MzE2LCJqdGkiOiIxOTY2NjdjYmQxNTQ0MDNmYWYzMWQ2YWI2OGE5NTE0YSIsInVzZXJfaWQiOiIyIn0.AvDTQ20QIZQn2aAjumVDqB95ALqCF37Ba9BSzI4zdRk	2026-02-04 15:31:56.31085+05:30	2026-02-11 15:31:56+05:30	2	196667cbd154403faf31d6ab68a9514a
4	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3MDgxMDM5OSwiaWF0IjoxNzcwMjA1NTk5LCJqdGkiOiI3MDVhMWNkNzIzZDQ0OGMwYmZlZTdhZGMyNjQwMTQ2MyIsInVzZXJfaWQiOiIyIn0.8Bd-FcSHaT0TYBpEQAV1adzLIdnfQfaGESjf3hr1X6U	2026-02-04 17:16:39.163258+05:30	2026-02-11 17:16:39+05:30	2	705a1cd723d448c0bfee7adc26401463
5	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3MDgxMzI5MywiaWF0IjoxNzcwMjA4NDkzLCJqdGkiOiJkZmYyNzcyNDNiZmY0MDg0Yjg2MzIxMjljMWM4YTFmNyIsInVzZXJfaWQiOiIyIn0.aH9E96q30Hv1KCH6BRzu6O7tkcXZsr0a0mQttx4JOnY	2026-02-04 18:04:53.351749+05:30	2026-02-11 18:04:53+05:30	2	dff277243bff4084b8632129c1c8a1f7
6	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3MDgxNDEyNiwiaWF0IjoxNzcwMjA5MzI2LCJqdGkiOiJjZjlkYTgzODUwNjA0NTAyOTdmNzdiM2RiZWJlM2I0NCIsInVzZXJfaWQiOiIyIn0.2BlEQc2TgaKWsoBxR4cCY376G0rEpH8WsaoueNFlKRs	2026-02-04 18:18:46.026325+05:30	2026-02-11 18:18:46+05:30	2	cf9da8385060450297f77b3dbebe3b44
7	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3MDgxNDIyNywiaWF0IjoxNzcwMjA5NDI3LCJqdGkiOiIyNzViZDVhMTNiZWU0MGIyYjkzZTFhMWQxNzQ3MjViZSIsInVzZXJfaWQiOiIyIn0.hhT7QZJkk02f8DIA34Na2e21vh2n_dpfkGR_NNlHl6Q	2026-02-04 18:20:27.013603+05:30	2026-02-11 18:20:27+05:30	2	275bd5a13bee40b2b93e1a1d174725be
8	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3MDgxNDU5NSwiaWF0IjoxNzcwMjA5Nzk1LCJqdGkiOiI4M2RmMzc2NzYxMTg0MDdjOWZkZGFlYjhiNGZkMDc3MCIsInVzZXJfaWQiOiIyIn0.Jq_QXaV3i4N2s92yexa5lNHvlJjA4tQpAGfNWuTTCo4	2026-02-04 18:26:35.290187+05:30	2026-02-11 18:26:35+05:30	2	83df37676118407c9fddaeb8b4fd0770
9	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3MDgxNDY3MSwiaWF0IjoxNzcwMjA5ODcxLCJqdGkiOiJkMTU4NDZjZTcxMzY0ZGE0YTMxNTA1NWRmNDg0OWM3NCIsInVzZXJfaWQiOiIyIn0.NC-aLdmJjn3rc6S2JphpvnVt5xyz_J7QD0WCKOzPmL8	2026-02-04 18:27:51.512556+05:30	2026-02-11 18:27:51+05:30	2	d15846ce71364da4a315055df4849c74
10	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3MDgxNDg0MiwiaWF0IjoxNzcwMjEwMDQyLCJqdGkiOiJhZjBhZTkzMjc1Mjg0Njg0OGI3NTFmYTFjMzVmMjNmNSIsInVzZXJfaWQiOiIyIn0.EPK5b-nUhFlHDrImCDQlDNwVdRNyzIP-LPP-s6SwhQY	2026-02-04 18:30:42.622002+05:30	2026-02-11 18:30:42+05:30	2	af0ae932752846848b751fa1c35f23f5
11	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3MDg3MzM0NiwiaWF0IjoxNzcwMjY4NTQ2LCJqdGkiOiI5MjQyMmM3NzIyYzM0OTI2YTE4MWIxOGRiZTQwYzFjOSIsInVzZXJfaWQiOiIyIn0.L9NcM0H-BmUbjRablL6jWuNj2n6BAJOWZg17qx4nmUw	2026-02-05 10:45:46.565946+05:30	2026-02-12 10:45:46+05:30	2	92422c7722c34926a181b18dbe40c1c9
12	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3MDg3Mzg4MiwiaWF0IjoxNzcwMjY5MDgyLCJqdGkiOiJiYjI3YzUyNGViYTI0MGMzYmM1OGQ4OGEzMzVlYmZlMiIsInVzZXJfaWQiOiIyIn0.5sF4nv3cfFBaLh6LemYH3TSDkV3INxJsuXc3hUF_CBU	2026-02-05 10:54:42.107738+05:30	2026-02-12 10:54:42+05:30	2	bb27c524eba240c3bc58d88a335ebfe2
13	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3MDg3Mzk0OSwiaWF0IjoxNzcwMjY5MTQ5LCJqdGkiOiIxZDI5OWU2NmRhY2I0N2U3YWQwOWViMDA5ZjAxOTA1ZCIsInVzZXJfaWQiOiIyIn0.WT1RhxNUxAnlJlfd8g80fU8Y_RpGD6YZ-uqiZzSFKKM	2026-02-05 10:55:49.509297+05:30	2026-02-12 10:55:49+05:30	2	1d299e66dacb47e7ad09eb009f01905d
14	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3MDg3NDYzOSwiaWF0IjoxNzcwMjY5ODM5LCJqdGkiOiJmMjY3NWRmMDlmODE0OWY1YmU5MzI1M2NmNDEzM2RlZCIsInVzZXJfaWQiOiIyIn0.Nnz6YogECN1tnrFbxsgKZxbhfuZSFdc1SwwFf7n2Gbg	2026-02-05 11:07:19.757462+05:30	2026-02-12 11:07:19+05:30	2	f2675df09f8149f5be93253cf4133ded
15	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3MDg4ODE2NiwiaWF0IjoxNzcwMjgzMzY2LCJqdGkiOiI1NzVmZjc5ZTU0ZGU0ODQzYmRhMjM3NmE0MzRhNmQ5YyIsInVzZXJfaWQiOiIxIn0.kqb-rVToNs00PXVhIWtd3x38xwRm2pz8b02IsX8ZB4c	2026-02-05 14:52:46.404621+05:30	2026-02-12 14:52:46+05:30	1	575ff79e54de4843bda2376a434a6d9c
16	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3MDg4ODg0OCwiaWF0IjoxNzcwMjg0MDQ4LCJqdGkiOiIzYjIxMmQwNTNjYjM0ZDlmODQzYTk3MWQxZjg2YjA4YyIsInVzZXJfaWQiOiIzIn0.EQNh9SuQvzVSwQynPiJk61IGHzvVJw-0_Y94noTYTpM	2026-02-05 15:04:08.92922+05:30	2026-02-12 15:04:08+05:30	3	3b212d053cb34d9f843a971d1f86b08c
17	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3MDg4OTg1OCwiaWF0IjoxNzcwMjg1MDU4LCJqdGkiOiIwOTA4ZTAyMzJiZjU0NTRmOGQyNzRkMTkxZTliYmVkOCIsInVzZXJfaWQiOiIzIn0.WCIUaCJcaA5-zBPnVeySlT-fIRxSW7Or_QnythQJ3Sw	2026-02-05 15:20:58.34098+05:30	2026-02-12 15:20:58+05:30	3	0908e0232bf5454f8d274d191e9bbed8
18	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3MDg5MTgxMiwiaWF0IjoxNzcwMjg3MDEyLCJqdGkiOiI0YjgxN2EzODQ2NzA0ZTUzOTQwNDg1ZjU4NzczNzY5ZCIsInVzZXJfaWQiOiIzIn0.GY_8QwSLN_jzcoK47M_orF51GY0zqVMhEMmNeGl1vqg	2026-02-05 15:53:32.003216+05:30	2026-02-12 15:53:32+05:30	3	4b817a3846704e53940485f58773769d
19	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3MDg5MTkxOCwiaWF0IjoxNzcwMjg3MTE4LCJqdGkiOiJkZDRhMjdjYzM5ZDM0NmE3ODFjNGRjNWJkNWQ5NDg1YSIsInVzZXJfaWQiOiIzIn0.K0vWrlshADbIYdFALW2OtyKiNh6z4CK-CJDf2N8Vn38	2026-02-05 15:55:18.520311+05:30	2026-02-12 15:55:18+05:30	3	dd4a27cc39d346a781c4dc5bd5d9485a
20	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3MDg5MjI0MSwiaWF0IjoxNzcwMjg3NDQxLCJqdGkiOiJkMTBlN2JhMWFiN2Q0ZWRjOWExOGUxM2FlYTNkZWYwNyIsInVzZXJfaWQiOiIzIn0.lsQKBWz8wc1k2N2dVJRvkDtDFXF5y-CzpWfAyeUASpA	2026-02-05 16:00:41.751096+05:30	2026-02-12 16:00:41+05:30	3	d10e7ba1ab7d4edc9a18e13aea3def07
21	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3MDg5MjYwNywiaWF0IjoxNzcwMjg3ODA3LCJqdGkiOiJiZTM4ZmUxMzE4NjU0YWQwOGVmYzNkMjc0NGU0OGFmNSIsInVzZXJfaWQiOiIzIn0.nz11uS8BHxIjiob5Uxx4DjZGE-soJeVgTXQMT0Ge5tg	2026-02-05 16:06:47.446979+05:30	2026-02-12 16:06:47+05:30	3	be38fe1318654ad08efc3d2744e48af5
22	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3MDg5MjY3NiwiaWF0IjoxNzcwMjg3ODc2LCJqdGkiOiJkMGI0MTUxM2EwNjk0NTQyYjIyOTg1M2UyM2I1YzVhMiIsInVzZXJfaWQiOiIyIn0.4Xnr1MMH8urAeKyG5N8TYUBGpm7fDcmhxuGQRnKGfhQ	2026-02-05 16:07:56.591327+05:30	2026-02-12 16:07:56+05:30	2	d0b41513a0694542b229853e23b5c5a2
23	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3MDg5NTA4MCwiaWF0IjoxNzcwMjkwMjgwLCJqdGkiOiI3ZWMyZjM3YjY4ODI0YmZjOTI4Y2RlZWQ1YTY5OTNmZCIsInVzZXJfaWQiOiIyIn0.OEbVjaDJhY330vRkmUVfBIrj8V8lPodCxpjzxLSaqr0	2026-02-05 16:48:00.160503+05:30	2026-02-12 16:48:00+05:30	2	7ec2f37b68824bfc928cdeed5a6993fd
24	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3MDg5NTE5MCwiaWF0IjoxNzcwMjkwMzkwLCJqdGkiOiJlYWE1OTU1MDE1ZDY0ZGFmOTVlNzlkOWQ0NGJmMGQxMSIsInVzZXJfaWQiOiIyIn0.x06xxGsBwtf_t7r32irMdXoukHdo5VTT7mPoei1orX4	2026-02-05 16:49:50.943689+05:30	2026-02-12 16:49:50+05:30	2	eaa5955015d64daf95e79d9d44bf0d11
25	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3MDg5NTQ5NSwiaWF0IjoxNzcwMjkwNjk1LCJqdGkiOiIzMjdkZTFiMmJhNjA0ZGQ5YWRmMDUxNzlmMjY5NzI1MSIsInVzZXJfaWQiOiIyIn0.DI3EBvguxnIVNVTPQeDOtQVj_XnDCeiVG3cBKLRC43E	2026-02-05 16:54:55.286241+05:30	2026-02-12 16:54:55+05:30	2	327de1b2ba604dd9adf05179f2697251
26	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3MTU4MTkzMCwiaWF0IjoxNzcwOTc3MTMwLCJqdGkiOiIxYjg5Y2FhZDUyNjU0MGY2YTA1MjhmNDc3ZGFjNDI0NyIsInVzZXJfaWQiOiIzIn0.65ssyPgg_iskyo4IirY4d0MqHoDJlVBl8r2RAksNwHo	2026-02-13 15:35:30.674097+05:30	2026-02-20 15:35:30+05:30	3	1b89caad526540f6a0528f477dac4247
27	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3MTgyNTk5MCwiaWF0IjoxNzcxMjIxMTkwLCJqdGkiOiI4YWM3YmZiZDkyYmY0NjA0YWYwNWUzNzBhNWNhMDgwYiIsInVzZXJfaWQiOiIzIn0.KQ6eTshiItLKoAolod3ysTXnT5zgkT5pCUQPsb0V3AU	2026-02-16 11:23:10.417967+05:30	2026-02-23 11:23:10+05:30	3	8ac7bfbd92bf4604af05e370a5ca080b
28	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3MTgyNjA4MSwiaWF0IjoxNzcxMjIxMjgxLCJqdGkiOiIxOTA3NTBjMGQ5N2E0OGJmYWNhZmM5Y2UzMDhlOTljOCIsInVzZXJfaWQiOiIzIn0.evUmUVgoSKKbpX_FaCDIfSVGhTOYJK9fIxEGNASBz3s	2026-02-16 11:24:41.416491+05:30	2026-02-23 11:24:41+05:30	3	190750c0d97a48bfacafc9ce308e99c8
29	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3MTk5MjY1MCwiaWF0IjoxNzcxMzg3ODUwLCJqdGkiOiI4OGIxMmVhODE3NzM0NTlhYjI1NjgzYjkwNzEwZGNkMSIsInVzZXJfaWQiOiIzIn0.SN8w0xQqDdGmtz6oJWsRcL8kjHeNt6BLPNjh7TNk5FM	2026-02-18 09:40:50.98113+05:30	2026-02-25 09:40:50+05:30	3	88b12ea81773459ab25683b90710dcd1
30	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3MTk5NzMzMCwiaWF0IjoxNzcxMzkyNTMwLCJqdGkiOiJhNTZiNDg0MmYxNGY0YzdhOGY1ZjJlMGU2OTM1NTc4OCIsInVzZXJfaWQiOiIzIn0.B6IfExY0BZ6r_N87YG0uZs2tAENDE0kwsmHgZp4AjYM	2026-02-18 10:58:50.093379+05:30	2026-02-25 10:58:50+05:30	3	a56b4842f14f4c7a8f5f2e0e69355788
31	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3MjAxMTk3NCwiaWF0IjoxNzcxNDA3MTc0LCJqdGkiOiI1ZjA3MTM4MmFhZmI0Y2RkOTAzN2RlZTBhNDUwYTZlYiIsInVzZXJfaWQiOiIzIn0.YtQgtQG6ez5GltYa8l8tNCY_OvwFygnJ8DsLfEnE3rc	2026-02-18 15:02:54.502203+05:30	2026-02-25 15:02:54+05:30	3	5f071382aafb4cdd9037dee0a450a6eb
32	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3Mzk5ODYwMiwiaWF0IjoxNzczMzkzODAyLCJqdGkiOiJhN2E5MzFkMmY1MzE0MTU0OWIwNjEzMjY3NDQyMjViZSIsInVzZXJfaWQiOiIyIn0.SZdvjv0QDF_pQXpecsd8xywLAuWLWHOZrnXCbYRasEQ	2026-03-13 14:53:22.620427+05:30	2026-03-20 14:53:22+05:30	2	a7a931d2f53141549b061326744225be
33	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3Mzk5ODY2MiwiaWF0IjoxNzczMzkzODYyLCJqdGkiOiJmOWM1YTk4MzRkYTY0NDhhOWZmNzBjZWZmMmJkNDE0MSIsInVzZXJfaWQiOiIzIn0.51o3St2npT0RIt0WGbahEprVbh6XgrbbTENiMSufmPA	2026-03-13 14:54:22.074356+05:30	2026-03-20 14:54:22+05:30	3	f9c5a9834da6448a9ff70ceff2bd4141
34	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3Mzk5OTYxNCwiaWF0IjoxNzczMzk0ODE0LCJqdGkiOiIzODI5YzM2Mzk5ZGY0Y2UxYjNjM2ZmMTVlN2U5MjIyNSIsInVzZXJfaWQiOiIzIn0.Za2s8WiXOE8W0N95PfOvhBHsq-DfuzS7s43j7U3I2U0	2026-03-13 15:10:14.114263+05:30	2026-03-20 15:10:14+05:30	3	3829c36399df4ce1b3c3ff15e7e92225
35	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3OTI2MjQyMywiaWF0IjoxNzc4NjU3NjIzLCJqdGkiOiIwMzE5YjBiZGVjYzY0ODZjYWExYTcxYmEwZmQ2NzJiMyIsInVzZXJfaWQiOiIzIn0.W6Wla-eRNBUKkMat--R9rxHxymqO4yMmqtWkrJxaBOE	2026-05-13 13:03:43.067052+05:30	2026-05-20 13:03:43+05:30	3	0319b0bdecc6486caa1a71ba0fd672b3
36	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3OTI3MzE5NCwiaWF0IjoxNzc4NjY4Mzk0LCJqdGkiOiI4YjVkZjI0NDg3ODc0YmIwOTUwZjI3MWIxMzcwYzM3MCIsInVzZXJfaWQiOiIyIn0.HIBAoAC4rLmLHu96d8DMRbCt26qiB5FekNkby1KhIBc	2026-05-13 16:03:14.721563+05:30	2026-05-20 16:03:14+05:30	2	8b5df24487874bb0950f271b1370c370
37	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3OTI3Mzg4NiwiaWF0IjoxNzc4NjY5MDg2LCJqdGkiOiIxMDgxYzhjNDhmZGU0ZDUyOTU5NmIxNzg3ZDc1YzgzYSIsInVzZXJfaWQiOiIyIn0.uF20Hom37QpOxpVqUwOOipfpVBzKLDwgjvgxcCuNiKI	2026-05-13 16:14:46.050339+05:30	2026-05-20 16:14:46+05:30	2	1081c8c48fde4d529596b1787d75c83a
38	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3OTI3Mzk5MywiaWF0IjoxNzc4NjY5MTkzLCJqdGkiOiJjYmU1NjJhZmRjNDE0N2E1ODhjNGZlYTMwMTRlYzg4MSIsInVzZXJfaWQiOiIyIn0.pBYXBCCIESOBrVT-vW2cwb2Nc7PD0TFmOKNF4T25YLI	2026-05-13 16:16:33.452418+05:30	2026-05-20 16:16:33+05:30	2	cbe562afdc4147a588c4fea3014ec881
39	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3OTI3NDgwOCwiaWF0IjoxNzc4NjcwMDA4LCJqdGkiOiIwN2RkYTgyZmI0OGY0NzE1YjJiMGIwMzU0NWVkYjZiNSIsInVzZXJfaWQiOiIxIn0.dCmgs-Xo2ZdvWwcaggrf4NwjURD5FB0I3UwlIujMlvA	2026-05-13 16:30:08.644249+05:30	2026-05-20 16:30:08+05:30	1	07dda82fb48f4715b2b0b03545edb6b5
40	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3OTI3NDg5MiwiaWF0IjoxNzc4NjcwMDkyLCJqdGkiOiI4MmNjYzYxOGY5MGE0NjYyOTI4ZGUyNjZkODY5OTM5MyIsInVzZXJfaWQiOiIyIn0.X8jG9WTcCo5Ter3LeTg19a25_D4m8nsGU9TNlDZ6BRg	2026-05-13 16:31:32.654371+05:30	2026-05-20 16:31:32+05:30	2	82ccc618f90a4662928de266d8699393
41	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3OTI3NDkzNywiaWF0IjoxNzc4NjcwMTM3LCJqdGkiOiI5Yjc3ZTViNjU1Zjc0NGE3OGZiNTBhYmUzZDAzYWMyNiIsInVzZXJfaWQiOiIxIn0.si-TM304JqKm6e9D1O4SPHs77V0Bq_nEYnk4-9jStGg	2026-05-13 16:32:17.738293+05:30	2026-05-20 16:32:17+05:30	1	9b77e5b655f744a78fb50abe3d03ac26
42	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3OTI3OTA4MCwiaWF0IjoxNzc4Njc0MjgwLCJqdGkiOiJkOTdiMGFkMGI4NzI0ZWQwYjc2ODMzYTIzMzUxYmUzNiIsInVzZXJfaWQiOiIyIn0.cwLl9jttQzeo0uSnlnLlNvF1hoL9H6TSQlePVX4u07Y	2026-05-13 17:41:20.341174+05:30	2026-05-20 17:41:20+05:30	2	d97b0ad0b8724ed0b76833a23351be36
43	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3OTI3OTgxOCwiaWF0IjoxNzc4Njc1MDE4LCJqdGkiOiJiOTBiMzk3NmM4OTU0ZWFlOTY3OGNkZDNlMjEwNTZhNiIsInVzZXJfaWQiOiIxIn0.ZckUEcTNNNkxoCYQuGfxMZ95cPDFofV9OAJjjo0iXKw	2026-05-13 17:53:38.01529+05:30	2026-05-20 17:53:38+05:30	1	b90b3976c8954eae9678cdd3e21056a6
44	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3OTM0MTI5NiwiaWF0IjoxNzc4NzM2NDk2LCJqdGkiOiI2ZmM5YzZiMzE3Nzc0OTY0YTVhMTkwZDdiNjY0YjgyMiIsInVzZXJfaWQiOiIxIn0.wAGwQysZroxDxIziJfiSJ_NAP1VTogUj2oMi_AQc50w	2026-05-14 10:58:16.432234+05:30	2026-05-21 10:58:16+05:30	1	6fc9c6b317774964a5a190d7b664b822
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: nike
--

COPY public.users (id, password, last_login, is_superuser, first_name, last_name, is_staff, is_active, date_joined, username, email, phone, role, is_verified, created_at, updated_at) FROM stdin;
3	!io8LQ8x41wBD8sorl3QGZKmDwZPna0G9kIDmXa4H	\N	f			f	t	2026-02-05 15:03:13.796959+05:30	Rohit	maityamarkumar97@gmail.com	8017988495	admin	t	2026-02-05 15:03:13.797195+05:30	2026-02-05 15:03:13.8009+05:30
2	!HQQxkHkM6M86IxOf13TmiKTA2lvo0UiCk2uD1o9Q	\N	f			f	t	2026-02-04 15:13:03.932621+05:30	amar	amar.maity@delostylestudio.com	9903823389	user	t	2026-02-04 15:13:03.932865+05:30	2026-02-04 15:13:03.935156+05:30
1	pbkdf2_sha256$1200000$6jC04K7AvBB6pTK4n2kMST$bs5c9I9AZA6YZ2yzaf9aUrWTmcQIfTamqnasnUhV7v0=	\N	t			t	t	2026-02-04 14:24:58.551241+05:30	Amar	amarmaity243@gmail.com	\N	admin	t	2026-02-04 14:24:59.176601+05:30	2026-02-04 14:24:59.176607+05:30
\.


--
-- Data for Name: users_groups; Type: TABLE DATA; Schema: public; Owner: nike
--

COPY public.users_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: users_user_permissions; Type: TABLE DATA; Schema: public; Owner: nike
--

COPY public.users_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nike
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nike
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nike
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 80, true);


--
-- Name: customer_details_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nike
--

SELECT pg_catalog.setval('public.customer_details_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nike
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nike
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 19, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nike
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 42, true);


--
-- Name: master_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nike
--

SELECT pg_catalog.setval('public.master_category_id_seq', 4, true);


--
-- Name: product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nike
--

SELECT pg_catalog.setval('public.product_id_seq', 1, false);


--
-- Name: product_image_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nike
--

SELECT pg_catalog.setval('public.product_image_id_seq', 1, false);


--
-- Name: product_variant_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nike
--

SELECT pg_catalog.setval('public.product_variant_id_seq', 1, false);


--
-- Name: product_variant_image_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nike
--

SELECT pg_catalog.setval('public.product_variant_image_id_seq', 1, false);


--
-- Name: sub_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nike
--

SELECT pg_catalog.setval('public.sub_category_id_seq', 1, true);


--
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nike
--

SELECT pg_catalog.setval('public.token_blacklist_blacklistedtoken_id_seq', 11, true);


--
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nike
--

SELECT pg_catalog.setval('public.token_blacklist_outstandingtoken_id_seq', 44, true);


--
-- Name: users_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nike
--

SELECT pg_catalog.setval('public.users_groups_id_seq', 1, false);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nike
--

SELECT pg_catalog.setval('public.users_id_seq', 3, true);


--
-- Name: users_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nike
--

SELECT pg_catalog.setval('public.users_user_permissions_id_seq', 1, false);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: customer_details customer_details_c_email_key; Type: CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.customer_details
    ADD CONSTRAINT customer_details_c_email_key UNIQUE (c_email);


--
-- Name: customer_details customer_details_c_mobile_key; Type: CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.customer_details
    ADD CONSTRAINT customer_details_c_mobile_key UNIQUE (c_mobile);


--
-- Name: customer_details customer_details_pkey; Type: CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.customer_details
    ADD CONSTRAINT customer_details_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: master_category master_category_boys_id_key; Type: CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.master_category
    ADD CONSTRAINT master_category_boys_id_key UNIQUE (name);


--
-- Name: master_category master_category_pkey; Type: CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.master_category
    ADD CONSTRAINT master_category_pkey PRIMARY KEY (id);


--
-- Name: master_category master_category_slug_key; Type: CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.master_category
    ADD CONSTRAINT master_category_slug_key UNIQUE (slug);


--
-- Name: product_image product_image_pkey; Type: CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.product_image
    ADD CONSTRAINT product_image_pkey PRIMARY KEY (id);


--
-- Name: product product_pkey; Type: CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_pkey PRIMARY KEY (id);


--
-- Name: product product_sku_key; Type: CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_sku_key UNIQUE (sku);


--
-- Name: product product_slug_key; Type: CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_slug_key UNIQUE (slug);


--
-- Name: product_variant_image product_variant_image_pkey; Type: CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.product_variant_image
    ADD CONSTRAINT product_variant_image_pkey PRIMARY KEY (id);


--
-- Name: product_variant product_variant_pkey; Type: CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.product_variant
    ADD CONSTRAINT product_variant_pkey PRIMARY KEY (id);


--
-- Name: product_variant product_variant_sku_key; Type: CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.product_variant
    ADD CONSTRAINT product_variant_sku_key UNIQUE (sku);


--
-- Name: sub_category sub_category_master_category_id_name_8f12e89a_uniq; Type: CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.sub_category
    ADD CONSTRAINT sub_category_master_category_id_name_8f12e89a_uniq UNIQUE (master_category_id, name);


--
-- Name: sub_category sub_category_name_key; Type: CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.sub_category
    ADD CONSTRAINT sub_category_name_key UNIQUE (name);


--
-- Name: sub_category sub_category_pkey; Type: CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.sub_category
    ADD CONSTRAINT sub_category_pkey PRIMARY KEY (id);


--
-- Name: sub_category sub_category_slug_key; Type: CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.sub_category
    ADD CONSTRAINT sub_category_slug_key UNIQUE (slug);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_pkey PRIMARY KEY (id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_key; Type: CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_key UNIQUE (token_id);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq; Type: CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq UNIQUE (jti);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_pkey PRIMARY KEY (id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users_groups users_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_pkey PRIMARY KEY (id);


--
-- Name: users_groups users_groups_user_id_group_id_fc7788e8_uniq; Type: CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_user_id_group_id_fc7788e8_uniq UNIQUE (user_id, group_id);


--
-- Name: users users_phone_key; Type: CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_phone_key UNIQUE (phone);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users_user_permissions users_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: users_user_permissions users_user_permissions_user_id_permission_id_3b86cbdf_uniq; Type: CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_user_id_permission_id_3b86cbdf_uniq UNIQUE (user_id, permission_id);


--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: nike
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: nike
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: nike
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: nike
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: customer_details_c_email_7b41a3ba_like; Type: INDEX; Schema: public; Owner: nike
--

CREATE INDEX customer_details_c_email_7b41a3ba_like ON public.customer_details USING btree (c_email varchar_pattern_ops);


--
-- Name: customer_details_c_mobile_d856dc2f_like; Type: INDEX; Schema: public; Owner: nike
--

CREATE INDEX customer_details_c_mobile_d856dc2f_like ON public.customer_details USING btree (c_mobile varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: nike
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: nike
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: nike
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: nike
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: master_category_boys_id_393831f0_like; Type: INDEX; Schema: public; Owner: nike
--

CREATE INDEX master_category_boys_id_393831f0_like ON public.master_category USING btree (name varchar_pattern_ops);


--
-- Name: master_category_slug_162c3688_like; Type: INDEX; Schema: public; Owner: nike
--

CREATE INDEX master_category_slug_162c3688_like ON public.master_category USING btree (slug varchar_pattern_ops);


--
-- Name: product_image_product_id_8b9355c5; Type: INDEX; Schema: public; Owner: nike
--

CREATE INDEX product_image_product_id_8b9355c5 ON public.product_image USING btree (product_id);


--
-- Name: product_sku_1e15f61e_like; Type: INDEX; Schema: public; Owner: nike
--

CREATE INDEX product_sku_1e15f61e_like ON public.product USING btree (sku varchar_pattern_ops);


--
-- Name: product_slug_c4732ed0_like; Type: INDEX; Schema: public; Owner: nike
--

CREATE INDEX product_slug_c4732ed0_like ON public.product USING btree (slug varchar_pattern_ops);


--
-- Name: product_sub_category_id_969ff5f9; Type: INDEX; Schema: public; Owner: nike
--

CREATE INDEX product_sub_category_id_969ff5f9 ON public.product USING btree (sub_category_id);


--
-- Name: product_variant_image_variant_id_6f5d2f49; Type: INDEX; Schema: public; Owner: nike
--

CREATE INDEX product_variant_image_variant_id_6f5d2f49 ON public.product_variant_image USING btree (variant_id);


--
-- Name: product_variant_product_id_31eca93d; Type: INDEX; Schema: public; Owner: nike
--

CREATE INDEX product_variant_product_id_31eca93d ON public.product_variant USING btree (product_id);


--
-- Name: product_variant_sku_5514a590_like; Type: INDEX; Schema: public; Owner: nike
--

CREATE INDEX product_variant_sku_5514a590_like ON public.product_variant USING btree (sku varchar_pattern_ops);


--
-- Name: sub_category_master_category_id_2bd329d8; Type: INDEX; Schema: public; Owner: nike
--

CREATE INDEX sub_category_master_category_id_2bd329d8 ON public.sub_category USING btree (master_category_id);


--
-- Name: sub_category_name_42480096_like; Type: INDEX; Schema: public; Owner: nike
--

CREATE INDEX sub_category_name_42480096_like ON public.sub_category USING btree (name varchar_pattern_ops);


--
-- Name: sub_category_slug_c3e5d3d3_like; Type: INDEX; Schema: public; Owner: nike
--

CREATE INDEX sub_category_slug_c3e5d3d3_like ON public.sub_category USING btree (slug varchar_pattern_ops);


--
-- Name: token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like; Type: INDEX; Schema: public; Owner: nike
--

CREATE INDEX token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like ON public.token_blacklist_outstandingtoken USING btree (jti varchar_pattern_ops);


--
-- Name: token_blacklist_outstandingtoken_user_id_83bc629a; Type: INDEX; Schema: public; Owner: nike
--

CREATE INDEX token_blacklist_outstandingtoken_user_id_83bc629a ON public.token_blacklist_outstandingtoken USING btree (user_id);


--
-- Name: users_email_0ea73cca_like; Type: INDEX; Schema: public; Owner: nike
--

CREATE INDEX users_email_0ea73cca_like ON public.users USING btree (email varchar_pattern_ops);


--
-- Name: users_groups_group_id_2f3517aa; Type: INDEX; Schema: public; Owner: nike
--

CREATE INDEX users_groups_group_id_2f3517aa ON public.users_groups USING btree (group_id);


--
-- Name: users_groups_user_id_f500bee5; Type: INDEX; Schema: public; Owner: nike
--

CREATE INDEX users_groups_user_id_f500bee5 ON public.users_groups USING btree (user_id);


--
-- Name: users_phone_2b77170a_like; Type: INDEX; Schema: public; Owner: nike
--

CREATE INDEX users_phone_2b77170a_like ON public.users USING btree (phone varchar_pattern_ops);


--
-- Name: users_user_permissions_permission_id_6d08dcd2; Type: INDEX; Schema: public; Owner: nike
--

CREATE INDEX users_user_permissions_permission_id_6d08dcd2 ON public.users_user_permissions USING btree (permission_id);


--
-- Name: users_user_permissions_user_id_92473840; Type: INDEX; Schema: public; Owner: nike
--

CREATE INDEX users_user_permissions_user_id_92473840 ON public.users_user_permissions USING btree (user_id);


--
-- Name: users_username_e8658fc8_like; Type: INDEX; Schema: public; Owner: nike
--

CREATE INDEX users_username_e8658fc8_like ON public.users USING btree (username varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: product_image product_image_product_id_8b9355c5_fk_product_id; Type: FK CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.product_image
    ADD CONSTRAINT product_image_product_id_8b9355c5_fk_product_id FOREIGN KEY (product_id) REFERENCES public.product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: product product_sub_category_id_969ff5f9_fk_sub_category_id; Type: FK CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_sub_category_id_969ff5f9_fk_sub_category_id FOREIGN KEY (sub_category_id) REFERENCES public.sub_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: product_variant_image product_variant_image_variant_id_6f5d2f49_fk_product_variant_id; Type: FK CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.product_variant_image
    ADD CONSTRAINT product_variant_image_variant_id_6f5d2f49_fk_product_variant_id FOREIGN KEY (variant_id) REFERENCES public.product_variant(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: product_variant product_variant_product_id_31eca93d_fk_product_id; Type: FK CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.product_variant
    ADD CONSTRAINT product_variant_product_id_31eca93d_fk_product_id FOREIGN KEY (product_id) REFERENCES public.product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sub_category sub_category_master_category_id_2bd329d8_fk_master_category_id; Type: FK CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.sub_category
    ADD CONSTRAINT sub_category_master_category_id_2bd329d8_fk_master_category_id FOREIGN KEY (master_category_id) REFERENCES public.master_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk; Type: FK CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk FOREIGN KEY (token_id) REFERENCES public.token_blacklist_outstandingtoken(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_user_id_83bc629a_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_user_id_83bc629a_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_groups users_groups_group_id_2f3517aa_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_group_id_2f3517aa_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_groups users_groups_user_id_f500bee5_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_user_id_f500bee5_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_permissions users_user_permissio_permission_id_6d08dcd2_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissio_permission_id_6d08dcd2_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_permissions users_user_permissions_user_id_92473840_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: nike
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_user_id_92473840_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict 58d8MixNif57Uh6ggGd6BFmqTi8PE7V4obmLYs5KMnpxW7auNOmrIdwzg7BEIy0

