export{ default as Customers} from "./customers/Customers"
export {default as Orders} from "./orders/Orders"
export{default as Users} from "./orders/Orders"
export {default as WebsiteContent} from "./website-content/WebsiteContent"
export {default as Settings} from "./settings/Settings"
export {default as Reports} from "./reports/Reports"
export{default as Products} from "./products/Products"
export {default as Payments} from "./payments/Payments"
export {default as DashboardHome} from "./dashboard/DashboardHome"