export { default as Shop } from "./Shop"
export { default as SingleProduct } from "./SingleProduct"
export { default as Cart } from "./Cart"
export { default as Register } from "./Register"
export { default as Login } from "./Login"
export { default as Profile } from "./user/Profile"
export { default as Contact } from "./Contact"
export { default as Home } from "./Home"
export{ default as Error} from "./Error"